/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interface;

import Code.Pessoa;
import java.awt.Color;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.JToggleButton;

/**
 *
 * @author Duke Mirage
 */
public class ConsultAltEntidade extends javax.swing.JFrame {

    public MenuPrincipal menu;
    
    public int indexEntidade;
    
    public ConsultAltEntidade(MenuPrincipal menu) {
        this.menu = menu;
        initComponents();
        
        getContentPane().setBackground(Color.DARK_GRAY);
    }
    public ConsultAltEntidade(){
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tituloTxt = new javax.swing.JLabel();
        subTituloTxt = new javax.swing.JLabel();
        cpftxt = new javax.swing.JLabel();
        jCpfBuscaTxt = new javax.swing.JTextField();
        Separador1 = new javax.swing.JSeparator();
        DadosEncontrados = new javax.swing.JLabel();
        NomeTxt = new javax.swing.JLabel();
        CpfTxt = new javax.swing.JLabel();
        DataNascTxt = new javax.swing.JLabel();
        TipoTxt = new javax.swing.JLabel();
        TelefoneTxt = new javax.swing.JLabel();
        EmailTxt = new javax.swing.JLabel();
        EndereçoTxt = new javax.swing.JLabel();
        jNomeTxt = new javax.swing.JTextField();
        jCpfTxt = new javax.swing.JTextField();
        TipoLabel = new javax.swing.JLabel();
        jDataNascTxt = new javax.swing.JTextField();
        jTelefoneTxt = new javax.swing.JTextField();
        jEmailTxt = new javax.swing.JTextField();
        jEnderecoTxt = new javax.swing.JTextField();
        jBtnVoltar = new javax.swing.JButton();
        jBtnRemover = new javax.swing.JButton();
        jBtnAvancar = new javax.swing.JButton();
        jBtnPesquisar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);

        tituloTxt.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        tituloTxt.setForeground(new java.awt.Color(255, 255, 255));
        tituloTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloTxt.setText("Consultar ou Alterar Cadastros");

        subTituloTxt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        subTituloTxt.setForeground(new java.awt.Color(255, 255, 255));
        subTituloTxt.setText("Consultar clientes ou funcionários por CPF");

        cpftxt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cpftxt.setForeground(new java.awt.Color(255, 255, 255));
        cpftxt.setText("CPF :");

        jCpfBuscaTxt.setBackground(new java.awt.Color(51, 51, 51));
        jCpfBuscaTxt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jCpfBuscaTxt.setForeground(new java.awt.Color(255, 255, 255));
        jCpfBuscaTxt.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        Separador1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        DadosEncontrados.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        DadosEncontrados.setForeground(new java.awt.Color(255, 255, 255));
        DadosEncontrados.setText("Dados encontrados");

        NomeTxt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        NomeTxt.setForeground(new java.awt.Color(255, 255, 255));
        NomeTxt.setText("Nome :");

        CpfTxt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        CpfTxt.setForeground(new java.awt.Color(255, 255, 255));
        CpfTxt.setText("CPF :");

        DataNascTxt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        DataNascTxt.setForeground(new java.awt.Color(255, 255, 255));
        DataNascTxt.setText("Data de Nasc :");

        TipoTxt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TipoTxt.setForeground(new java.awt.Color(255, 255, 255));
        TipoTxt.setText("Tipo :");

        TelefoneTxt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TelefoneTxt.setForeground(new java.awt.Color(255, 255, 255));
        TelefoneTxt.setText("Telefone :");

        EmailTxt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        EmailTxt.setForeground(new java.awt.Color(255, 255, 255));
        EmailTxt.setText("Email :");

        EndereçoTxt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        EndereçoTxt.setForeground(new java.awt.Color(255, 255, 255));
        EndereçoTxt.setText("Endereço :");

        jNomeTxt.setBackground(new java.awt.Color(51, 51, 51));
        jNomeTxt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jNomeTxt.setForeground(new java.awt.Color(255, 255, 255));
        jNomeTxt.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jNomeTxt.setDisabledTextColor(new java.awt.Color(204, 204, 204));

        jCpfTxt.setBackground(new java.awt.Color(51, 51, 51));
        jCpfTxt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jCpfTxt.setForeground(new java.awt.Color(255, 255, 255));
        jCpfTxt.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jCpfTxt.setDisabledTextColor(new java.awt.Color(204, 204, 204));

        TipoLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TipoLabel.setForeground(new java.awt.Color(255, 255, 255));
        TipoLabel.setText("...");

        jDataNascTxt.setBackground(new java.awt.Color(51, 51, 51));
        jDataNascTxt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jDataNascTxt.setForeground(new java.awt.Color(255, 255, 255));
        jDataNascTxt.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jDataNascTxt.setDisabledTextColor(new java.awt.Color(204, 204, 204));

        jTelefoneTxt.setBackground(new java.awt.Color(51, 51, 51));
        jTelefoneTxt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTelefoneTxt.setForeground(new java.awt.Color(255, 255, 255));
        jTelefoneTxt.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jTelefoneTxt.setDisabledTextColor(new java.awt.Color(204, 204, 204));

        jEmailTxt.setBackground(new java.awt.Color(51, 51, 51));
        jEmailTxt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jEmailTxt.setForeground(new java.awt.Color(255, 255, 255));
        jEmailTxt.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jEmailTxt.setDisabledTextColor(new java.awt.Color(204, 204, 204));

        jEnderecoTxt.setBackground(new java.awt.Color(51, 51, 51));
        jEnderecoTxt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jEnderecoTxt.setForeground(new java.awt.Color(255, 255, 255));
        jEnderecoTxt.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jEnderecoTxt.setDisabledTextColor(new java.awt.Color(204, 204, 204));

        jBtnVoltar.setBackground(new java.awt.Color(51, 51, 51));
        jBtnVoltar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jBtnVoltar.setForeground(new java.awt.Color(255, 255, 255));
        jBtnVoltar.setText("Voltar");
        jBtnVoltar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jBtnVoltar.setBorderPainted(false);
        jBtnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnVoltarActionPerformed(evt);
            }
        });

        jBtnRemover.setBackground(new java.awt.Color(51, 51, 51));
        jBtnRemover.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jBtnRemover.setForeground(new java.awt.Color(255, 255, 255));
        jBtnRemover.setText("Remover");
        jBtnRemover.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jBtnRemover.setBorderPainted(false);
        jBtnRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnRemoverActionPerformed(evt);
            }
        });

        jBtnAvancar.setBackground(new java.awt.Color(51, 51, 51));
        jBtnAvancar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jBtnAvancar.setForeground(new java.awt.Color(255, 255, 255));
        jBtnAvancar.setText("Alterar");
        jBtnAvancar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jBtnAvancar.setBorderPainted(false);
        jBtnAvancar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAvancarActionPerformed(evt);
            }
        });

        jBtnPesquisar.setBackground(new java.awt.Color(51, 51, 51));
        jBtnPesquisar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jBtnPesquisar.setForeground(new java.awt.Color(255, 255, 255));
        jBtnPesquisar.setText("Pesquisar");
        jBtnPesquisar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jBtnPesquisar.setBorderPainted(false);
        jBtnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnPesquisarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 41, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBtnVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBtnRemover, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(75, 75, 75)
                        .addComponent(jBtnAvancar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(NomeTxt)
                        .addGap(18, 18, 18)
                        .addComponent(jNomeTxt))
                    .addComponent(DadosEncontrados)
                    .addComponent(Separador1, javax.swing.GroupLayout.PREFERRED_SIZE, 523, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(CpfTxt)
                        .addGap(31, 31, 31)
                        .addComponent(jCpfTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(TipoTxt)
                        .addGap(18, 18, 18)
                        .addComponent(TipoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(DataNascTxt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jDataNascTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(TelefoneTxt)
                        .addGap(18, 18, 18)
                        .addComponent(jTelefoneTxt))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(EmailTxt)
                        .addGap(18, 18, 18)
                        .addComponent(jEmailTxt))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(EndereçoTxt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jEnderecoTxt)))
                .addGap(36, 36, 36))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(172, 172, 172)
                        .addComponent(subTituloTxt))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tituloTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cpftxt)
                                .addGap(18, 18, 18)
                                .addComponent(jCpfBuscaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jBtnPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(tituloTxt)
                .addGap(18, 18, 18)
                .addComponent(subTituloTxt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCpfBuscaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cpftxt)
                    .addComponent(jBtnPesquisar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Separador1, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DadosEncontrados)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NomeTxt)
                    .addComponent(jNomeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CpfTxt)
                    .addComponent(TipoTxt)
                    .addComponent(jCpfTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TipoLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DataNascTxt)
                    .addComponent(jDataNascTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TelefoneTxt)
                    .addComponent(jTelefoneTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EmailTxt)
                    .addComponent(jEmailTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EndereçoTxt)
                    .addComponent(jEnderecoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnVoltar)
                    .addComponent(jBtnRemover)
                    .addComponent(jBtnAvancar))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnVoltarActionPerformed
        //Botão voltar
        menu.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jBtnVoltarActionPerformed

    private void jBtnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnPesquisarActionPerformed
                // Aqui vamos pesquisar o cpf da entidade
        Boolean cpfEncontrado = false;
        
        if(!getjCpfBuscaTxt().getText().equals("")){
            //Uma rapida busca no banco de dados para verificar se o CPF digitado é igual ao de alguma entidade
            for(Pessoa entidade : menu.banco.entidades){
                
                if(entidade.cpf.equals(getjCpfBuscaTxt().getText())){
                    //CPF encontrado!
                    cpfEncontrado = true;
                    preencherCampos(entidade);
                    
                    
                    ativaItens(true);
                    
                    indexEntidade = menu.banco.entidades.indexOf(entidade);
                }
            }
            
            //Mensagens de alerta, cpf encontrado ou não
            if(cpfEncontrado){
                JOptionPane.showMessageDialog(null, "Cadastro encontrado!");
            }else{
                JOptionPane.showMessageDialog(null, "O CPF informado não foi encontrado!");
            }
            
        }else{
            
            JOptionPane.showMessageDialog(null, "Informe um CPF para continuar!");
        }
        
    }//GEN-LAST:event_jBtnPesquisarActionPerformed

    private void jBtnRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnRemoverActionPerformed
        // Vamos remover a entidade visualizada
        //Uma rapida verificação se o usuário quer mesmo remover a entidade;

        
        Object[] options = { "Sim", "Não" };
        //OBS: opc pode ser 0 ou 1, sendo 0 se o botão sim for apertado.
        int opc = JOptionPane.showOptionDialog(null, "Tem certeza que quer REMOVER esse CADASTRO?", "Remover", JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE, null, options, options[0]);
        
        if(opc == 0){
            //Botão confirmar apertado, entidade removida!
            menu.banco.entidades.remove(indexEntidade);
            
            resetInfos();
            ativaItens(false);
            
            JOptionPane.showMessageDialog(null, "Cadastro removido com sucesso!");
        }
    }//GEN-LAST:event_jBtnRemoverActionPerformed

    private void jBtnAvancarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAvancarActionPerformed
        // Alterando a entidade
        int opc;
        
        Object[] options = { "Sim", "Não" };
        //OBS: opc pode ser 0 ou 1, sendo 0 se o botão sim for apertado.
        opc = JOptionPane.showOptionDialog(null, "Tem certeza que quer ALTERAR esse CADASTRO?", "Alteração", JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE, null, options, options[0]);
        
        if(opc == 0){
            //Botão confirmar apertado, entidade alterada!
            alterarEnt(menu.banco.entidades.get(indexEntidade));
            
            resetInfos();
            ativaItens(false);
            
            JOptionPane.showMessageDialog(null, "Cadastro alterado com sucesso!");
            
        }
        
    }//GEN-LAST:event_jBtnAvancarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsultAltEntidade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsultAltEntidade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsultAltEntidade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultAltEntidade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConsultAltEntidade().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CpfTxt;
    private javax.swing.JLabel DadosEncontrados;
    private javax.swing.JLabel DataNascTxt;
    private javax.swing.JLabel EmailTxt;
    private javax.swing.JLabel EndereçoTxt;
    private javax.swing.JLabel NomeTxt;
    private javax.swing.JSeparator Separador1;
    private javax.swing.JLabel TelefoneTxt;
    private javax.swing.JLabel TipoLabel;
    private javax.swing.JLabel TipoTxt;
    private javax.swing.JLabel cpftxt;
    private javax.swing.JButton jBtnAvancar;
    private javax.swing.JButton jBtnPesquisar;
    private javax.swing.JButton jBtnRemover;
    private javax.swing.JButton jBtnVoltar;
    private javax.swing.JTextField jCpfBuscaTxt;
    private javax.swing.JTextField jCpfTxt;
    private javax.swing.JTextField jDataNascTxt;
    private javax.swing.JTextField jEmailTxt;
    private javax.swing.JTextField jEnderecoTxt;
    private javax.swing.JTextField jNomeTxt;
    private javax.swing.JTextField jTelefoneTxt;
    private javax.swing.JLabel subTituloTxt;
    private javax.swing.JLabel tituloTxt;
    // End of variables declaration//GEN-END:variables

    
    //Funções personalizadas
    
    private void preencherCampos(Pessoa entidade){
        //Passando uma entidade como parametro, podemos pegar seus dados e setar nos campos
        if(entidade.tipoEntidade == 1){
        TipoLabel.setText("Cliente");}else{ TipoLabel.setText("Funcionário");}
        jNomeTxt.setText(entidade.nome);
        jDataNascTxt.setText(entidade.dataNasc);
        jCpfTxt.setText(entidade.cpf);
        jEmailTxt.setText(entidade.email);
        jEnderecoTxt.setText(entidade.endereco);
        jTelefoneTxt.setText(entidade.telefone);
        
    }
    
    private void alterarEnt(Pessoa entidade){
        
        entidade.nome = getjNomeTxt().getText();
        entidade.cpf = getjCpfTxt().getText();
        entidade.dataNasc = getjDataNascTxt().getText();
        entidade.email = getjEmailTxt().getText();
        entidade.telefone = getjTelefoneTxt().getText();
        entidade.endereco = getjEnderecoTxt().getText();
    } 
    
    public void resetInfos(){
        getTipoLabel().setText("...");
        jCpfBuscaTxt.setText(null);
        jNomeTxt.setText(null);
        jDataNascTxt.setText(null);
        jCpfTxt.setText(null);
        jEmailTxt.setText(null);
        jEnderecoTxt.setText(null);
        jTelefoneTxt.setText(null);
    }
    
    //Reativando itens
    
    public void ativaItens(Boolean ativador){
        
        jNomeTxt.setEditable(ativador);
        jDataNascTxt.setEditable(ativador);
        jCpfTxt.setEditable(ativador);
        jEmailTxt.setEditable(ativador);
        jEnderecoTxt.setEditable(ativador);
        jTelefoneTxt.setEditable(ativador);
        jBtnRemover.setEnabled(ativador);
        jBtnAvancar.setEnabled(ativador);
        
    }
    
    //Getters and Setters
    
    
    public JLabel getTipoLabel() {
        return TipoLabel;
    }

    public void setTipoLabel(JLabel TipoLabel) {
        this.TipoLabel = TipoLabel;
    }

    public JButton getjBtnAvancar() {
        return jBtnAvancar;
    }

    public void setjBtnAvancar(JButton jBtnAvancar) {
        this.jBtnAvancar = jBtnAvancar;
    }

    public JButton getjBtnPesquisar() {
        return jBtnPesquisar;
    }

    public void setjBtnPesquisar(JButton jBtnPesquisar) {
        this.jBtnPesquisar = jBtnPesquisar;
    }

    

    public JButton getjBtnRemover() {
        return jBtnRemover;
    }

    public void setjBtnRemover(JButton jBtnRemover) {
        this.jBtnRemover = jBtnRemover;
    }

    public JButton getjBtnVoltar() {
        return jBtnVoltar;
    }

    public void setjBtnVoltar(JButton jBtnVoltar) {
        this.jBtnVoltar = jBtnVoltar;
    }

    public JTextField getjCpfBuscaTxt() {
        return jCpfBuscaTxt;
    }

    public void setjCpfBuscaTxt(JTextField jCpfBuscaTxt) {
        this.jCpfBuscaTxt = jCpfBuscaTxt;
    }

    public JTextField getjCpfTxt() {
        return jCpfTxt;
    }

    public void setjCpfTxt(JTextField jCpfTxt) {
        this.jCpfTxt = jCpfTxt;
    }

    public JTextField getjDataNascTxt() {
        return jDataNascTxt;
    }

    public void setjDataNascTxt(JTextField jDataNascTxt) {
        this.jDataNascTxt = jDataNascTxt;
    }

    public JTextField getjEmailTxt() {
        return jEmailTxt;
    }

    public void setjEmailTxt(JTextField jEmailTxt) {
        this.jEmailTxt = jEmailTxt;
    }

    public JTextField getjEnderecoTxt() {
        return jEnderecoTxt;
    }

    public void setjEnderecoTxt(JTextField jEnderecoTxt) {
        this.jEnderecoTxt = jEnderecoTxt;
    }

    public JTextField getjNomeTxt() {
        return jNomeTxt;
    }

    public void setjNomeTxt(JTextField jNomeTxt) {
        this.jNomeTxt = jNomeTxt;
    }

    public JTextField getjTelefoneTxt() {
        return jTelefoneTxt;
    }

    public void setjTelefoneTxt(JTextField jTelefoneTxt) {
        this.jTelefoneTxt = jTelefoneTxt;
    }

}
