/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interface;

import Code.Ordem;
import Code.Pessoa;
import java.awt.Color;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Duke Mirage
 */
public class ConsultaOrdem extends javax.swing.JFrame {

    public MenuPrincipal menu;
    public AlteracoesOrdens altOrdem = new AlteracoesOrdens(this);
    
    //Variaveis para controle;
    public int indexCliente;
    public int indexOrdem;
    
    public ConsultaOrdem(MenuPrincipal menu) {
        this.menu = menu;
        initComponents();
        
        getContentPane().setBackground(Color.DARK_GRAY);
    }
    
    public ConsultaOrdem(){
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tituloTxt = new javax.swing.JLabel();
        CpfTxt = new javax.swing.JLabel();
        jCpfBuscaTxt = new javax.swing.JTextField();
        jBtnPesquisa = new javax.swing.JButton();
        Separador1 = new javax.swing.JSeparator();
        PedidosEncontrados = new javax.swing.JLabel();
        DadosGerais = new javax.swing.JLabel();
        ClienteTxt = new javax.swing.JLabel();
        MotivoTxt = new javax.swing.JLabel();
        DataInitTxt = new javax.swing.JLabel();
        OrcamentoFinalTxt = new javax.swing.JLabel();
        containerTabela = new javax.swing.JScrollPane();
        tabelaIds = new javax.swing.JTable();
        jBtnVoltar = new javax.swing.JButton();
        jBtnAvancar = new javax.swing.JButton();
        ClienteLabel = new javax.swing.JLabel();
        MotivoLabel = new javax.swing.JLabel();
        DataInitLabel = new javax.swing.JLabel();
        OrcamentoFLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        tituloTxt.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        tituloTxt.setForeground(new java.awt.Color(255, 255, 255));
        tituloTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloTxt.setText("Consultar Ordem de Serviço");

        CpfTxt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        CpfTxt.setForeground(new java.awt.Color(255, 255, 255));
        CpfTxt.setText("CPF do Cliente :");

        jCpfBuscaTxt.setBackground(new java.awt.Color(51, 51, 51));
        jCpfBuscaTxt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jCpfBuscaTxt.setForeground(new java.awt.Color(255, 255, 255));
        jCpfBuscaTxt.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jBtnPesquisa.setBackground(new java.awt.Color(51, 51, 51));
        jBtnPesquisa.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jBtnPesquisa.setForeground(new java.awt.Color(255, 255, 255));
        jBtnPesquisa.setText("Pesquisar");
        jBtnPesquisa.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jBtnPesquisa.setBorderPainted(false);
        jBtnPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnPesquisaActionPerformed(evt);
            }
        });

        Separador1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        PedidosEncontrados.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        PedidosEncontrados.setForeground(new java.awt.Color(255, 255, 255));
        PedidosEncontrados.setText("Pedidos encontrados");

        DadosGerais.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        DadosGerais.setForeground(new java.awt.Color(255, 255, 255));
        DadosGerais.setText("Dados Gerais do pedido");

        ClienteTxt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ClienteTxt.setForeground(new java.awt.Color(255, 255, 255));
        ClienteTxt.setText("Cliente :");

        MotivoTxt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        MotivoTxt.setForeground(new java.awt.Color(255, 255, 255));
        MotivoTxt.setText("Motivo :");

        DataInitTxt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        DataInitTxt.setForeground(new java.awt.Color(255, 255, 255));
        DataInitTxt.setText("Data de Inicio :");

        OrcamentoFinalTxt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        OrcamentoFinalTxt.setForeground(new java.awt.Color(255, 255, 255));
        OrcamentoFinalTxt.setText("Orçamento Final :");

        tabelaIds.setBackground(new java.awt.Color(51, 51, 51));
        tabelaIds.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        tabelaIds.setForeground(new java.awt.Color(255, 255, 255));
        tabelaIds.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Identificador"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaIds.getTableHeader().setResizingAllowed(false);
        tabelaIds.getTableHeader().setReorderingAllowed(false);
        tabelaIds.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaIdsMouseClicked(evt);
            }
        });
        containerTabela.setViewportView(tabelaIds);
        if (tabelaIds.getColumnModel().getColumnCount() > 0) {
            tabelaIds.getColumnModel().getColumn(0).setResizable(false);
        }

        jBtnVoltar.setBackground(new java.awt.Color(51, 51, 51));
        jBtnVoltar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jBtnVoltar.setForeground(new java.awt.Color(255, 255, 255));
        jBtnVoltar.setText("Voltar");
        jBtnVoltar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jBtnVoltar.setBorderPainted(false);
        jBtnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnVoltarActionPerformed(evt);
            }
        });

        jBtnAvancar.setBackground(new java.awt.Color(51, 51, 51));
        jBtnAvancar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jBtnAvancar.setForeground(new java.awt.Color(255, 255, 255));
        jBtnAvancar.setText("Avançar");
        jBtnAvancar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jBtnAvancar.setBorderPainted(false);
        jBtnAvancar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAvancarActionPerformed(evt);
            }
        });

        ClienteLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ClienteLabel.setForeground(new java.awt.Color(255, 255, 255));
        ClienteLabel.setText("...");

        MotivoLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        MotivoLabel.setForeground(new java.awt.Color(255, 255, 255));
        MotivoLabel.setText("...");

        DataInitLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        DataInitLabel.setForeground(new java.awt.Color(255, 255, 255));
        DataInitLabel.setText("...");

        OrcamentoFLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        OrcamentoFLabel.setForeground(new java.awt.Color(255, 255, 255));
        OrcamentoFLabel.setText("...");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Separador1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PedidosEncontrados)
                            .addComponent(containerTabela, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(MotivoTxt)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(MotivoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ClienteTxt)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ClienteLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(DadosGerais)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(DataInitTxt)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(DataInitLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(OrcamentoFinalTxt)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(OrcamentoFLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBtnVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBtnAvancar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(44, 44, 44))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(159, 159, 159)
                        .addComponent(CpfTxt)
                        .addGap(18, 18, 18)
                        .addComponent(jCpfBuscaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jBtnPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(201, 201, 201)
                        .addComponent(tituloTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(186, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(tituloTxt)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CpfTxt)
                    .addComponent(jCpfBuscaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnPesquisa))
                .addGap(18, 18, 18)
                .addComponent(Separador1, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PedidosEncontrados)
                    .addComponent(DadosGerais))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ClienteTxt)
                            .addComponent(ClienteLabel))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(MotivoTxt)
                            .addComponent(MotivoLabel))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(DataInitTxt)
                            .addComponent(DataInitLabel))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(OrcamentoFinalTxt)
                            .addComponent(OrcamentoFLabel)))
                    .addComponent(containerTabela, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBtnVoltar)
                    .addComponent(jBtnAvancar))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnPesquisaActionPerformed
        //Aqui vamos pesquisar o cliente e colocar na tabela seus pedidos!
        
        Boolean cpfEncontrado = false;
        
        if(!getjCpfBuscaTxt().getText().equals("")){
        
            for(Pessoa cliente : menu.banco.entidades){
            
            if(cliente.cpf.equals(getjCpfBuscaTxt().getText()) && cliente.tipoEntidade == 1){
                
                cpfEncontrado = true;
                
                
                //Esse indice vai ser usado para manipulações futuras....
                //Com ele ja temos exatamente o cliente que precisamos sem refazer varreduras...
                indexCliente = menu.banco.entidades.indexOf(cliente);
                
                //Desenhar a tabela
                DefaultTableModel table = (DefaultTableModel) tabelaIds.getModel();
                table.setNumRows(0);
                
                //Para cada ordem na lista de ordens do cliente, será add uma nova linha com a id da mesma na tabela
                for(Ordem ord : cliente.ordens){
                    table.addRow(new Object[]{ord.getId()});
                }
                
                if(table.getRowCount() == 0){
                //Se não houver ordens
                    JOptionPane.showMessageDialog(null, "Esse cliente não possui nenhuma ordem de serviço.");
                }else if(table.getRowCount() > 0){
                    JOptionPane.showMessageDialog(null, "Cliente encontrado! Escolha uma ordem de serviço clicando em seu número de identificação na tabela.");
                }
                
              }
            }
        
            if(!cpfEncontrado){
                //Entidade não encontrada apos a varredura no BD
                JOptionPane.showMessageDialog(null, "Cliente não encontrado!");
            }
        
        }else{
            JOptionPane.showMessageDialog(null, "O campo CPF não pode estar VAZIO.");
        }
        
        
        
        
            
    }//GEN-LAST:event_jBtnPesquisaActionPerformed

    private void jBtnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnVoltarActionPerformed
        // Simplesmente VOLTAR
        menu.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jBtnVoltarActionPerformed

    private void jBtnAvancarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAvancarActionPerformed
        // Seguir com as alterações na ordem....
        altOrdem.setVisible(true);
        altOrdem.setIndex(indexCliente, indexOrdem);
        altOrdem.setarCampos(menu.banco.entidades.get(indexCliente).ordens.get(indexOrdem));
        setVisible(false);
        
    }//GEN-LAST:event_jBtnAvancarActionPerformed

    private void tabelaIdsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaIdsMouseClicked
        //Quando o mouse clicar em alguma ordem
        //Primeiro pegamos o indice da linha
        indexOrdem = tabelaIds.getSelectedRow();
        
        ativaItens(true);//só para ativa/desativar o botão avançar...
        
        //Bom, aqui precisamos de uma ORDEM para passar como parametro.
        //Então ao chamar a função setarCampos, passei a ordem[indice X] de um cliente[indice X] da lista de entidades do banco
        
        //Ficou assim: ClasseMenu.VariavelBanco.ListaEntidadeDoBanco.EntidadeDoIndice(indexCliente).ListaOrdemDessaEntidade.OrdemDoIndice(pos)
        setarCampos(menu.banco.entidades.get(indexCliente).ordens.get(indexOrdem));
        
        //Com base nessa ordem escolhida acima, vamos alterar os campos...
    
    }//GEN-LAST:event_tabelaIdsMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsultaOrdem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsultaOrdem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsultaOrdem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultaOrdem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConsultaOrdem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ClienteLabel;
    private javax.swing.JLabel ClienteTxt;
    private javax.swing.JLabel CpfTxt;
    private javax.swing.JLabel DadosGerais;
    private javax.swing.JLabel DataInitLabel;
    private javax.swing.JLabel DataInitTxt;
    private javax.swing.JLabel MotivoLabel;
    private javax.swing.JLabel MotivoTxt;
    private javax.swing.JLabel OrcamentoFLabel;
    private javax.swing.JLabel OrcamentoFinalTxt;
    private javax.swing.JLabel PedidosEncontrados;
    private javax.swing.JSeparator Separador1;
    private javax.swing.JScrollPane containerTabela;
    private javax.swing.JButton jBtnAvancar;
    private javax.swing.JButton jBtnPesquisa;
    private javax.swing.JButton jBtnVoltar;
    private javax.swing.JTextField jCpfBuscaTxt;
    private javax.swing.JTable tabelaIds;
    private javax.swing.JLabel tituloTxt;
    // End of variables declaration//GEN-END:variables

    //Funções personalizadas
    public void resetInfos(){
        
        //Aqui criamos uma varivel (tabelaId) para manipular a tabela de IDS 
        DefaultTableModel tabelaId = (DefaultTableModel) tabelaIds.getModel();
        
        //Aqui setamos o numero de linhas da tabela em 0
        tabelaId.setNumRows(0);
        
        //Outros campos...
        jCpfBuscaTxt.setText(null);
        ClienteLabel.setText(null);
        MotivoLabel.setText(null);
        DataInitLabel.setText(null);
        OrcamentoFLabel.setText(null);
        
    }
    
    public void ativaItens(Boolean ativador){
        jBtnAvancar.setEnabled(ativador);
    }
    
    //Essa função vai setar os campos da descrição da ordem , ao clicarmos na id dela na tabela
    public void setarCampos(Ordem ordem){
        
        ClienteLabel.setText(ordem.nome);
        MotivoLabel.setText(ordem.motivo);
        DataInitLabel.setText(ordem.dataIni);
        OrcamentoFLabel.setText("R$ " + ordem.orcamentoFinal);
        
    }
    
    //Getters and Setters
    
    
    public JTextField getjCpfBuscaTxt() {
        return jCpfBuscaTxt;
    }

    public void setjCpfBuscaTxt(JTextField jCpfBuscaTxt) {
        this.jCpfBuscaTxt = jCpfBuscaTxt;
    }

    public JLabel getClienteLabel() {
        return ClienteLabel;
    }

    public void setClienteLabel(JLabel ClienteLabel) {
        this.ClienteLabel = ClienteLabel;
    }

    public JLabel getDataInitLabel() {
        return DataInitLabel;
    }

    public void setDataInitLabel(JLabel DataInitLabel) {
        this.DataInitLabel = DataInitLabel;
    }

    public JLabel getMotivoLabel() {
        return MotivoLabel;
    }

    public void setMotivoLabel(JLabel MotivoLabel) {
        this.MotivoLabel = MotivoLabel;
    }

    public JLabel getOrcamentoFLabel() {
        return OrcamentoFLabel;
    }

    public void setOrcamentoFLabel(JLabel OrcamentoFLabel) {
        this.OrcamentoFLabel = OrcamentoFLabel;
    }


    
}
